type    "model\Property.js" ^
		"model\BaseElement.js" ^
		"model\BusinessService.js" ^
            "model\Artifact.js" ^
               "model\Annotation.js" ^
               "model\Group.js" ^
               "model\Lane.js" ^
            "model\Collaboration.js" ^
            "model\CustomProperty.js" ^
            "model\DataAssociation.js" ^
            "model\DataState.js" ^
            "model\EventDefinition.js" ^
               "model\CancelEventDefinition.js" ^
               "model\CompensateEventDefinition.js" ^
               "model\ConditionalEventDefinition.js" ^
               "model\ErrorEventDefinition.js" ^
               "model\EscalationEventDefinition.js" ^
               "model\LinkEventDefinition.js" ^
               "model\MessageEventDefinition.js" ^
               "model\SignalEventDefinition.js" ^
               "model\TerminateEventDefinition.js" ^
               "model\TimerEventDefinition.js" ^
            "model\EventListener.js" ^
               "model\ExecutionListener.js" ^
               "model\TaskListener.js" ^
            "model\FlowElement.js" ^
               "model\Connector.js" ^
                  "model\Association.js" ^
                  "model\MessageFlow.js" ^
                  "model\SequenceFlow.js" ^
               "model\DataObject.js" ^
		       "model\FlowNode.js" ^
		          "model\Activity.js" ^
		             "model\CallActivity.js" ^
		             "model\EventSubprocessCollapsed.js" ^
		             "model\SubProcess.js" ^
		                "model\EventSubProcess.js" ^
		           	 "model\Task.js" ^
		           	    "model\BusinessRuleTask.js" ^
						"model\ManualTask.js" ^
						"model\ReceiveTask.js" ^
						"model\ScriptTask.js" ^
						"model\SendTask.js" ^
						"model\ServiceTask.js" ^
						   "model\VOExchangeTask.js" ^
						"model\DefaultTaskHandlingDefinition.js" ^
						"model\DefaultParticipantDefinition.js" ^
						"model\DefaultNoticeDefinition.js" ^
						"model\UserTaskPolicyControl.js" ^
						"model\UserTask.js" ^
				  "model\Event.js" ^
				     "model\CatchEvent.js" ^
				        "model\CompensationBoundaryEvent.js" ^
				        "model\CancelBoundaryEvent.js" ^
				        "model\ConditionalBoundaryEvent.js" ^
				        "model\ErrorBoundaryEvent.js" ^
				        "model\EscalationBoundaryEvent.js" ^
				        "model\LinkBoundaryEvent.js" ^
				        "model\MessageBoundaryEvent.js" ^
				        "model\MultiParallelBoundaryEvent.js" ^
				        "model\MultipleBoundaryEvent.js" ^
				        "model\SignalBoundaryEvent.js" ^
				        "model\TimerBoundaryEvent.js" ^
				        "model\IntermediateCatchEvent.js" ^
				           "model\IntermediateCatchCancelEvent.js" ^
				           "model\IntermediateCatchCompensationEvent.js" ^
				           "model\IntermediateCatchConditionalEvent.js" ^
				           "model\IntermediateCatchErrorEvent.js" ^
				           "model\IntermediateCatchEscalationEvent.js" ^
				           "model\IntermediateCatchLinkEvent.js" ^
				           "model\IntermediateCatchMessageEvent.js" ^
				           "model\IntermediateCatchMultiParallelEvent.js" ^
				           "model\IntermediateCatchMultipleEvent.js" ^
				           "model\IntermediateCatchSignalEvent.js" ^
				           "model\IntermediateCatchTimerEvent.js" ^
				        "model\StartEvent.js" ^
				           "model\StartCompensateEvent.js" ^
				           "model\StartConditionalEvent.js" ^
				           "model\StartErrorEvent.js" ^
				           "model\StartEscalationEvent.js" ^
				           "model\StartMessageEvent.js" ^
				           "model\StartMultipleEvent.js" ^
				           "model\StartSignalEvent.js" ^
				           "model\StartTimerEvent.js" ^
				     "model\ThrowEvent.js" ^
				        "model\EndEvent.js" ^
				           "model\EndCancelEvent.js" ^
				           "model\EndCompensationEvent.js" ^
				           "model\EndErrorEvent.js" ^
				           "model\EndEsacalationEvent.js" ^
				           "model\EndMessageEvent.js" ^
				           "model\EndMultipleEvent.js" ^
				           "model\EndSignalEvent.js" ^
				           "model\EndTerminateEvent.js" ^
				        "model\ImplicitThrowEvent.js" ^
				        "model\IntermediateThrowEvent.js" ^
				           "model\IntermediateThrowCompensationEvent.js" ^
				           "model\IntermediateThrowEscalationEvent.js" ^
				           "model\IntermediateThrowLinkEvent.js" ^
				           "model\IntermediateThrowMessageEvent.js" ^
				           "model\IntermediateThrowMultipleEvent.js" ^
				           "model\IntermediateThrowSignalEvent.js" ^
				 "model\Gateway.js" ^
  					"model\ComplexGateway.js" ^
  					"model\EventGateway.js" ^
  					"model\EventBasedGateway.js" ^
  					"model\ExclusiveGateway.js" ^
  					"model\InclusiveGateway.js" ^
  					"model\parallelGateway.js" ^
              "model\FlowElementsContainer.js" ^
                 "model\Process.js" ^
              "model\FormProperty.js" ^
              "model\FormValue.js" ^
              "model\ItemAwareElement.js" ^
              "model\MessageRef.js" ^
              "model\OperationRef.js" ^
              "model\Participant.js" ^
              "model\pool.js" ^
              "service\PluginService.js" ^
              "model\signal.js" ^
        > .\model.js