/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package test.biz.rcvbill.vo;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class TestRcvBillDetail extends SuperVO {
	private java.lang.String parentid;
	private java.lang.String id;
	private java.lang.String materiel;
	private nc.vo.pub.lang.UFDouble price;
	private nc.vo.pub.lang.UFDouble quanlity;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PARENTID = "parentid";
	public static final String ID = "id";
	public static final String MATERIEL = "materiel";
	public static final String PRICE = "price";
	public static final String QUANLITY = "quanlity";
			
	/**
	 * 属性parentid的Getter方法.属性名：parentPK
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getParentid () {
		return parentid;
	}   
	/**
	 * 属性parentid的Setter方法.属性名：parentPK
	 * 创建日期:
	 * @param newParentid java.lang.String
	 */
	public void setParentid (java.lang.String newParentid ) {
	 	this.parentid = newParentid;
	} 	  
	/**
	 * 属性id的Getter方法.属性名：detail id
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getId () {
		return id;
	}   
	/**
	 * 属性id的Setter方法.属性名：detail id
	 * 创建日期:
	 * @param newId java.lang.String
	 */
	public void setId (java.lang.String newId ) {
	 	this.id = newId;
	} 	  
	/**
	 * 属性materiel的Getter方法.属性名：materiel
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getMateriel () {
		return materiel;
	}   
	/**
	 * 属性materiel的Setter方法.属性名：materiel
	 * 创建日期:
	 * @param newMateriel java.lang.String
	 */
	public void setMateriel (java.lang.String newMateriel ) {
	 	this.materiel = newMateriel;
	} 	  
	/**
	 * 属性price的Getter方法.属性名：price
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getPrice () {
		return price;
	}   
	/**
	 * 属性price的Setter方法.属性名：price
	 * 创建日期:
	 * @param newPrice nc.vo.pub.lang.UFDouble
	 */
	public void setPrice (nc.vo.pub.lang.UFDouble newPrice ) {
	 	this.price = newPrice;
	} 	  
	/**
	 * 属性quanlity的Getter方法.属性名：quanlity
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getQuanlity () {
		return quanlity;
	}   
	/**
	 * 属性quanlity的Setter方法.属性名：quanlity
	 * 创建日期:
	 * @param newQuanlity nc.vo.pub.lang.UFDouble
	 */
	public void setQuanlity (nc.vo.pub.lang.UFDouble newQuanlity ) {
	 	this.quanlity = newQuanlity;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "parentid";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "id";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "rcvbilldetail";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "rcvbilldetail";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public TestRcvBillDetail() {
		super();	
	}    
} 


